uall:
#	g++ -Wall parsingTableGenerate.cpp -o tableGen
#	g++ -Wall first-follow.cpp -o firstFollow
	g++ -Wall leftFactoring.cpp -o factor
#	g++ -Wall parse.cpp -o parsing
clean:
	rm -rf tableGen
	rm -rf firstFollow
	rm -rf parsing
	rm -rf factor
